### ISSUE TITLE
怎么刷新头部数据呀

### ISSUE THREAD

**Issue by liaoxiaochen** [flyOfYW/YWExcel#5]
我看reload方法只更新了中间数据，却没有头部数据的更新

**Comment by flyOfYW** [comment]
不好意思，当时写这个的时候，没有考虑到头部刷新的事件，最近更新一个了，支持刷新头部以及单元格点击事件，https://github.com/flyOfYW/YWTableExcel

**Comment by liaoxiaochen** [comment]
谢谢您！
